services:
  starlight-docs:
    build:
      context: .
      args:
        # Pasa la variable del host al contenedor al construir
        - URL_REPO_DOCS=${URL_REPO_DOCS}
    container_name: starlight
    restart: unless-stopped
    ports:
      - "8080:8080"