name: Deploy Local Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Docker
        env:
          URL_REPO_DOCS: ${{ secrets.URL_REPO_DOCS }}
        run: |
          docker compose up -d --build
          docker image prune -f